apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  name: first-vela-app-2
  annotations:
    backstage.oam.dev/system: "first-vela-app"
spec:
  components:
    - name: express-server-same-system
      type: webservice
      properties:
        image: oamdev/hello-world
        ports:
          - port: 8000
            expose: true
      traits:
        - type: backstage-location
          properties:
            type: url
            targets:
              - "https://raw.githubusercontent.com/kubevela-contrib/backstage-plugin-kubevela/main/examples/backstage-user2.yaml"
        - type: backstage
          properties:
            type: website
            lifecycle: production
            owner: user:napptive
