apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  name: first-vela-app
  annotations:
    backstage.oam.dev/owner: "napptive-maintainers"
    backstage.oam.dev/domain: "vela-backstage-demo"
    backstage.oam.dev/description: "This is a sample application to test the integration of KubeVela with Backstage."
    backstage.oam.dev/title: "First Vela App"
    backstage.oam.dev/tags: "first-demo, vela"
spec:
  components:
    - name: express-server
      type: webservice
      properties:
        image: oamdev/hello-world
        ports:
          - port: 8000
            expose: true
      traits:
        - type: backstage
          properties:
            type: website
            lifecycle: production
            owner: user:napptive
            description: "This is a sample application to test the integration of KubeVela with Backstage."
            title: "Hello World"
            tags:
              - "hello-world"
            annotations:
              backstage.io/view-url: https://github.com/activa-prefapp/backstage-kubevela/blob/backstage-demo/examples-integration/app.yaml
              backstage.io/edit-url: https://github.com/activa-prefapp/backstage-kubevela/blob/backstage-demo/examples-integration/app.yaml
              backstage.io/source-location: url:https://github.com/activa-prefapp/backstage-kubevela
              github.com/project-slug: kubevela-contrib/backstage-plugin-kubevela
              github.com/team-slug: kubevela/maintainers
            labels:
              velaapp: demo
            links:
              - url: "https://github.com/activa-prefapp/documentation/blob/main/README.md"
                title: "vela-doc"
                type: "docs"