apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: prefapp
spec:
  profile:
    displayName: Luca
    email: prefapp.test@prefapp.com
    picture: https://avatars.githubusercontent.com/u/14019297?v=4
  memberOf: [napptive-maintainers]