apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  name: backstage
  namespace: vela-system
spec:
  components:
    - type: webservice
      name: backstage
      properties:
        image: ghcr.io/activa-prefapp/backstage-test:b0e3471fd0ecbe3596c93a43192c8135c795fbd6
        imagePullSecrets: [git-registry-secret]
        exposeType: ClusterIP
        ports:
          - port: 7007
            protocol: TCP
            expose: true