name: Docker Build and Publish
on:
  push:
    branches:
      - backstage-demo
      # - main
    paths:
      - "vela-backstage-demo/**"

env:
  IMAGE_NAME: backstage-test
  IMAGE_TAG: ${{ github.sha }}

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Build Docker image
        run: DOCKER_BUILDKIT=1 docker build -t ghcr.io/${{ github.repository_owner }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }} -f vela-backstage-demo/Dockerfile .

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.REGISTRY_TOKEN }}

      - name: Push Docker image to GitHub Container Registry
        run: docker push ghcr.io/${{ github.repository_owner }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}